name: Deploy to IBM Cloud Foundry

description: Deploy an application to Cloud Foundry on IBM Cloud

branding:
  icon: upload-cloud
  color: blue

inputs:
  IBM_CLOUD_API_KEY:
    description: IBM Cloud API key
    required: true
  IBM_CLOUD_CF_API:
    description: IBM Cloud Foundry API endpoint
    required: true
  IBM_CLOUD_CF_ORG:
    description: IBM Cloud Foundry organization name
    required: true
  IBM_CLOUD_CF_SPACE:
    description: IBM Cloud Foundry space name
    required: true

runs:
  using: "composite"
  steps:
    - name: Install IBM Cloud CLI
      run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
      shell: bash
    - name: Install Cloud Foundry CLI
      run: ibmcloud cf install
      shell: bash
    - name: Authenticate with IBM Cloud CLI
      run: ibmcloud login --apikey "${{ inputs.IBM_CLOUD_API_KEY }}" --no-region -g Default
      shell: bash
    - name: Target a Cloud Foundry org and space
      run: ibmcloud target --cf-api "${{ inputs.IBM_CLOUD_CF_API }}" -o "${{ inputs.IBM_CLOUD_CF_ORG }}" -s "${{ inputs.IBM_CLOUD_CF_SPACE }}"
      shell: bash
    - name: Deploy to Cloud Foundry
      run: ibmcloud cf push
      shell: bash
